# Generated by Django 3.2.8 on 2022-07-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sep', '0005_user_description_user_tagline_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tagline',
        ),
    ]
